### ISSUE TITLE
Got different next-item for a single test data during testing

### ISSUE THREAD

**Issue by np-n** [ahmedrashed-ml/CARCA#11]
Hello @ahmedrashed-ml, I have predicted the scores of the next items for test data, but I found something different than my expectation, scores are not similar for a single test data If I infer multiple times. This is how I have predicted the rank for the next items.
```
predictions = -model.predict(sess, np.ones(args.maxlen)*u, [seq], item_idx, [seqcxt], testitemscxt) 
predictions = predictions[0] # get scores only from predictions
score = -predictions.copy() # store actual prediction score, -(-(scores)) -> score
rank = predictions.argsort().argsort()[0]
print(rank)
```
In my opinion, rank must be similar on each test for single test data. But it is not happening. What is the possible solution to fix it? Thank you!

**Comment by ahmedrashed-ml** [comment]
You should get the same scores if you feed the same input history and target items. Otherwise, I would recommend you recheck your code again and make sure you have is_training as False during inference. Also, don't do any updates to the model weights during inference just load the model artifacts and do the inference.
